using System.IO;
using NUnit.Framework;
using UavSimulator.CityDemo;
using UnityEngine;

namespace UavSimulator.Tests
{
    public class OnnxClassifierServiceTests
    {
        [Test]
        public void Predict_ReturnsThreeProbabilitiesSummingToOne()
        {
            var modelPath = Path.Combine(Application.dataPath, "Tests/Resources/stub-tl-classifier.onnx");
            if (!File.Exists(modelPath))
            {
                Assert.Inconclusive(
                    "Stub ONNX classifier not present at " + modelPath +
                    "; it will be generated by Plan B Task 6 (tl_classifier).");
                return;
            }

            using var svc = new OnnxClassifierService(modelPath);
            var fake = new Color32[84 * 84];
            for (int i = 0; i < fake.Length; i++)
            {
                fake[i] = new Color32(128, 128, 128, 255);
            }

            var probs = svc.Predict(fake, 84, 84);

            Assert.AreEqual(3, probs.Length, "Classifier must return 3 probabilities.");
            float sum = probs[0] + probs[1] + probs[2];
            Assert.That(sum, Is.EqualTo(1f).Within(0.01f),
                "Softmax probabilities must sum to ~1 (got " + sum + ").");
        }
    }
}
