#!/usr/bin/env bash
# End-to-end smoke test для плагинного workflow CLI:
#   new → check archive → install → list → remove → list (cleanup verified)
#
# Не требует запущенного Unity или backend'а. Вся работа идёт с CLI-реестром
# `~/.rusim/plugin-registry.json` (или `${RUSIM_HOME}/plugin-registry.json`)
# и временной директорией.
#
# Запуск: bash scripts/validate_plugin_workflow.sh
# Exit code: 0 — все этапы прошли; ≠0 — конкретный этап отказал.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

PLUGIN_ID="${PLUGIN_ID:-vehicle.smoke.test.v1}"
PLUGIN_TYPE="${PLUGIN_TYPE:-vehicle}"
WORK_DIR="$(mktemp -d -t rusim-plugin-smoke-XXXXXX)"

cleanup() {
    rm -rf "$WORK_DIR"
    # Подстраховка: если smoke test падает после install, не оставляем мусор в реестре.
    ./rusim plugin remove "$PLUGIN_ID" >/dev/null 2>&1 || true
}
trap cleanup EXIT

echo "==> Working directory: $WORK_DIR"
echo "==> Plugin id: $PLUGIN_ID (type=$PLUGIN_TYPE)"

# 1. rusim plugin new — создаёт каркас плагина из шаблона
echo "==> Step 1: rusim plugin new"
./rusim plugin new \
    --type "$PLUGIN_TYPE" \
    --output-dir "$WORK_DIR" \
    --display-name "Smoke Test Plugin" \
    --description "Generated by validate_plugin_workflow.sh" \
    --author "smoke-test" \
    "$PLUGIN_ID" >"$WORK_DIR/new.log"

PLUGIN_DIR="$WORK_DIR/$PLUGIN_ID"
test -d "$PLUGIN_DIR" || { echo "FAIL: plugin scaffold not created at $PLUGIN_DIR"; exit 1; }
test -f "$PLUGIN_DIR/manifest.json" || { echo "FAIL: manifest.json missing in scaffold"; exit 1; }
test -f "$PLUGIN_DIR/descriptor.json" || { echo "FAIL: descriptor.json missing in scaffold"; exit 1; }

# 2. Собрать .rusim-plugin.zip — упаковываем поверхность плагина
echo "==> Step 2: build .rusim-plugin.zip"
ARCHIVE="$WORK_DIR/$PLUGIN_ID.rusim-plugin.zip"
(
    cd "$PLUGIN_DIR"
    # Берём только файлы, требуемые форматом архива (см. 7.6.1 в master-thesis/07).
    zip -q "$ARCHIVE" manifest.json descriptor.json
    if [ -f device-contract.json ]; then
        zip -qg "$ARCHIVE" device-contract.json
    fi
    if [ -f README.md ]; then
        zip -qg "$ARCHIVE" README.md
    fi
)
test -s "$ARCHIVE" || { echo "FAIL: archive empty or missing"; exit 1; }

# 3. rusim plugin install — регистрирует в CLI-реестре
echo "==> Step 3: rusim plugin install"
INSTALL_OUTPUT="$(./rusim plugin install "$ARCHIVE" 2>&1)"
echo "$INSTALL_OUTPUT" | grep -q '"action": "install"' \
    || { echo "FAIL: install did not report action=install"; echo "$INSTALL_OUTPUT"; exit 1; }
echo "$INSTALL_OUTPUT" | grep -q "\"pluginId\": \"$PLUGIN_ID\"" \
    || { echo "FAIL: install output missing pluginId=$PLUGIN_ID"; echo "$INSTALL_OUTPUT"; exit 1; }

# 4. rusim plugin list — наш plugin виден с тегом [user]
echo "==> Step 4: rusim plugin list (user плагин виден)"
./rusim plugin list --json >"$WORK_DIR/list.json"
cat >"$WORK_DIR/check_present.py" <<'PY'
import json
import sys

plugin_id = sys.argv[1]
with open(sys.argv[2]) as fh:
    data = json.load(fh)
matches = [it for it in data["items"] if it["pluginId"] == plugin_id]
if not matches:
    sys.stderr.write("FAIL: %s not in plugin list\n" % plugin_id)
    sys.exit(1)
if matches[0]["source"] != "user":
    sys.stderr.write("FAIL: %s source=%s, expected user\n" % (plugin_id, matches[0]["source"]))
    sys.exit(1)
PY
python3 "$WORK_DIR/check_present.py" "$PLUGIN_ID" "$WORK_DIR/list.json"

# 5. rusim plugin remove — убирает плагин из реестра
echo "==> Step 5: rusim plugin remove"
REMOVE_OUTPUT="$(./rusim plugin remove "$PLUGIN_ID" 2>&1)"
echo "$REMOVE_OUTPUT" | grep -q '"removed": true' \
    || { echo "FAIL: remove did not report removed=true"; echo "$REMOVE_OUTPUT"; exit 1; }

# 6. rusim plugin list — наш plugin исчез
echo "==> Step 6: rusim plugin list (cleanup проверен)"
./rusim plugin list --json >"$WORK_DIR/list2.json"
cat >"$WORK_DIR/check_absent.py" <<'PY'
import json
import sys

plugin_id = sys.argv[1]
with open(sys.argv[2]) as fh:
    data = json.load(fh)
matches = [it for it in data["items"] if it["pluginId"] == plugin_id]
if matches:
    sys.stderr.write("FAIL: %s still present after remove\n" % plugin_id)
    sys.exit(1)
PY
python3 "$WORK_DIR/check_absent.py" "$PLUGIN_ID" "$WORK_DIR/list2.json"

echo "==> OK: plugin workflow smoke test passed"
